[project]
name = "grpclient"
version = "0.1.0"
description = "gRPC UI client to handle requests and response for your microservices"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[project.scripts]
grpclient = "grpclient:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
